### ISSUE TITLE
[BUG] - Unable to build with Go 1.17

### ISSUE THREAD

**Issue by major** [vultr/vultr-cli#194]
**Describe the bug**

I'm trying to package vultr-cli on Fedora rawhide and it currently has Go 1.17 included. The compile fails when it reaches:

```
# github.com/vultr/vultr-cli/cmd/printer
_build/src/github.com/vultr/vultr-cli/cmd/printer/application.go:11:61: a.Type undefined (type govultr.Application has no field or method Type)
_build/src/github.com/vultr/vultr-cli/cmd/printer/application.go:11:69: a.Vendor undefined (type govultr.Application has no field or method Vendor)
_build/src/github.com/vultr/vultr-cli/cmd/printer/application.go:11:79: a.ImageID undefined (type govultr.Application has no field or method ImageID)
_build/src/github.com/vultr/vultr-cli/cmd/printer/instance.go:93:61: a.Type undefined (type govultr.Application has no field or method Type)
_build/src/github.com/vultr/vultr-cli/cmd/printer/instance.go:93:69: a.Vendor undefined (type govultr.Application has no field or method Vendor)
_build/src/github.com/vultr/vultr-cli/cmd/printer/kubernetes.go:7:25: undefined: govultr.Cluster
_build/src/github.com/vultr/vultr-cli/cmd/printer/kubernetes.go:47:17: undefined: govultr.Cluster
_build/src/github.com/vultr/vultr-cli/cmd/printer/kubernetes.go:82:27: undefined: govultr.NodePool
_build/src/github.com/vultr/vultr-cli/cmd/printer/kubernetes.go:107:19: undefined: govultr.NodePool
_build/src/github.com/vultr/vultr-cli/cmd/printer/kubernetes.go:127:27: undefined: govultr.Versions
_build/src/github.com/vultr/vultr-cli/cmd/printer/instance.go:93:69: too many errors
/usr/lib/golang/pkg/tool/linux_amd64/buildid -w $WORK/b160/_pkg_.a # internal
cp $WORK/b160/_pkg_.a /builddir/.cache/go-build/68/68e16097adb385305d51d942e9a8f3d6f0303cb2e7819ce7a35454322cec8291-d # internal
```
A full build log can be found in [Fedora COPR](https://download.copr.fedorainfracloud.org/results/mhayden/vultr-cli/fedora-rawhide-x86_64/02893148-golang-github-vultr-cli/builder-live.log.gz).

**To Reproduce**
1. Prepare a container build file:

```dockerfile
FROM registry.fedoraproject.org/fedora:rawhide
RUN curl -sLO https://download.copr.fedorainfracloud.org/results/mhayden/vultr-cli/fedora-rawhide-x86_64/02893148-golang-github-vultr-cli/golang-github-vultr-cli-2.8.4-1.fc36.src.rpm
RUN dnf -y install dnf-plugins-core rpm-build
RUN dnf -y builddep golang-github-vultr-cli-2.8.4-1.fc36.src.rpm
RUN rpmbuild --rebuild golang-github-vultr-cli-2.8.4-1.fc36.src.rpm
```
2. Build the container with `docker build` or `podman build`
3. Build fails at `github.com/vultr/vultr-cli/cmd/printer`

**Expected behavior**

I expect the compile to finish successfully.

**Screenshots**

See excerpt of build failure in first section.

**Comment by major** [comment]
@ddymko It looks like updating govultr was the culprit. I'll work with the package maintainer to get that done and then hopefully get vultr-cli packaged in Fedora soon! 🎉

Thanks for your help. There's probably not anything else to do on this issue now.
